name: Build Debian package

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine version
        id: ver
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
            VERSION="${VERSION#v}"   # strip leading v
          else
            VERSION="0.0.${GITHUB_RUN_NUMBER}"
          fi
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Install fpm
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev build-essential
          sudo gem install --no-document fpm

      - name: Stage files for package (app, desktop entry, icons)
        run: |
          mkdir -p packaging/pkgroot/opt/cryptools packaging/pkgroot/usr/bin packaging/pkgroot/usr/share/applications packaging/scripts
          cp -r *.py requirements.txt 2>/dev/null || true packaging/pkgroot/opt/cryptools/

          cat > packaging/pkgroot/usr/bin/cryptools <<'EOF'
          #!/usr/bin/env bash
          if [ -x /opt/cryptools/.venv/bin/python ]; then
            exec /opt/cryptools/.venv/bin/python /opt/cryptools/app.py "$@"
          else
            exec python3 /opt/cryptools/app.py "$@"
          fi
          EOF
          chmod +x packaging/pkgroot/usr/bin/cryptools

          mkdir -p packaging/pkgroot/usr/share/applications
          cp packaging/cryptools.desktop packaging/pkgroot/usr/share/applications/cryptools.desktop

          install_icon () {
            sz="$1"
            src="assets/icons/cryptools_${sz}x${sz}.png"
            dst="packaging/pkgroot/usr/share/icons/hicolor/${sz}x${sz}/apps"
            if [ -f "$src" ]; then
              mkdir -p "$dst"
              cp "$src" "$dst/cryptools.png"
            fi
          }
          install_icon 256
          install_icon 128
          install_icon 64
          install_icon 32
          install_icon 16

          cat > packaging/scripts/postinst <<'EOF'
          #!/usr/bin/env bash
          set -e
          if [ -f /opt/cryptools/requirements.txt ]; then
            apt-get update || true
            apt-get install -y python3-venv python3-pip || true
            python3 -m venv /opt/cryptools/.venv
            /opt/cryptools/.venv/bin/pip install --upgrade pip
            /opt/cryptools/.venv/bin/pip install -r /opt/cryptools/requirements.txt || true
          fi

          # refresh desktop + icon caches (best-effort)
          if command -v update-desktop-database >/dev/null 2>&1; then
            update-desktop-database -q || true
          fi
          if command -v gtk-update-icon-cache >/dev/null 2>&1; then
            gtk-update-icon-cache -f -q /usr/share/icons/hicolor || true
          fi
          EOF
          chmod +x packaging/scripts/postinst

      - name: Build .deb
        run: |
          cd packaging
          fpm -s dir -t deb \
            -n cryptools \
            -v "${{ steps.ver.outputs.version }}" \
            --architecture amd64 \
            -C pkgroot \
            --after-install scripts/postinst \
            -d "python3 (>= 3.8)" \
            -d "python3-tk" \
            -d "desktop-file-utils" \
            -d "hicolor-icon-theme" \
            --description "Crypto tools GUI" \
            --url "https://github.com/Ewsmyth/cryptools" \
            --license "MIT" \
            opt usr
          ls -l *.deb

      - name: Upload CI artifact
        uses: actions/upload-artifact@v4
        with:
          name: cryptools-deb-${{ steps.ver.outputs.version }}
          path: packaging/*.deb

      - name: Publish GitHub Release asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: packaging/*.deb
